x-default-logging: &default-logging
 driver: json-file
 options:
   max-size: 5m
   max-file: "2"
   max-buffer-size: 4m
   mode: non-blocking
   tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

services:
  go-feature-flag:
    container_name: go-feature-flag
    image: gofeatureflag/go-feature-flag
    logging: *default-logging
    ports:
      - 1031:1031
    volumes:
      # to generate go-feature-flag definition :
      # - https://gofeatureflag.org/editor
      - ./config:/goff
