x-default-logging: &default-logging
 driver: json-file
 options:
   max-size: 5m
   max-file: "2"
   max-buffer-size: 4m
   mode: non-blocking
   tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025
    logging: *default-logging
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1