x-default-logging: &default-logging
 driver: json-file
 options:
   max-size: 5m
   max-file: "2"
   max-buffer-size: 4m
   mode: non-blocking
   tag: "{{.Name}}|{{.ImageName}}|{{.ID}}"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_PASS: secret
      RABBITMQ_DEFAULT_USER: myuser
    ports:
      - 5672:5672
      - 15672:15672
    logging: *default-logging
